#!/bin/sh
#
# Warewulf Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Warewulf Copyright (c) 2003-2013, The Regents of the University of
# California, through Lawrence Berkeley National Laboratory (subject to
# receipt of any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
#
# Warewulf Copyright (c) 2019 System Fabric Works, Inc. <info@systemfabricworks.com>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# (1) Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# (2) Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# (3) Neither the name of the University of California, Lawrence Berkeley
# National Laboratory, U.S. Dept. of Energy nor the names of its contributors
# may be used to endorse or promote products derived from this software
# without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# You are under no obligation whatsoever to provide any bug fixes, patches,
# or upgrades to the features, functionality or performance of the source
# code ("Enhancements") to anyone; however, if you choose to make your
# Enhancements available either publicly, or directly to Lawrence Berkeley
# National Laboratory, without imposing a separate written license agreement
# for such Enhancements, then you hereby grant the following license: a
# non-exclusive, royalty-free perpetual license to install, use, modify,
# prepare derivative works, incorporate into other computer software,
# distribute, and sublicense such enhancements or derivative works thereof,
# in binary and source code form.
#

#
# Hook for mkinitramfs that copies in binaries required by warewulf
# provisioning.
#

set -e

if [ -z "$DESTDIR" ] ; then
	echo ERROR: DESTDIR not defined.
	exit 1
fi

. /usr/share/initramfs-tools/hook-functions

WW_STATE_DIR=$(wwconfig STATEDIR)
MACHINE=$(uname -m)
WW_INITRAMFS_DIR="$WW_STATE_DIR/warewulf/initramfs/$MACHINE"

copy_exec /sbin/e2fsck
copy_exec /sbin/fsck.ext2
copy_exec /sbin/fsck.ext3
copy_exec /sbin/fsck.ext4
copy_exec /sbin/mke2fs
copy_exec /sbin/mkfs.ext2
copy_exec /sbin/mkfs.ext3
copy_exec /sbin/mkfs.ext4
copy_exec /usr/bin/bsdtar /bin
copy_exec /sbin/parted
copy_exec /sbin/partprobe
copy_exec /usr/lib/x86_64-linux-gnu/libarchive.so.13 /lib/x86_64-linux-gnu

for FILE in "$DESTDIR/bin/"*; do
	if [ -f "$FILE" -a -x "$FILE" ] ; then
		copy_exec "$FILE" /usr/bin/$(basename "$FILE")
	fi
done

copy_exec "$WW_INITRAMFS_DIR/rootfs/etc/functions" /etc
rm -f "$DESTDIR/init"
copy_exec "$WW_INITRAMFS_DIR/rootfs//init" /
for FILE in "$WW_INITRAMFS_DIR/rootfs/sbin"/* ; do
	copy_exec "$FILE" /sbin
done

